services:
  pds-database:
    container_name: pds-database
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pds-db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgresql://postgres:postgres@pds-database:5432/pds-db
    ports:
      - '3000:3000'
    depends_on:
      pds-database:
        condition: service_healthy
    command: sh ./docker/scripts/start.sh

volumes:
  postgres_data: {}
